# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a867e0642a292681e84dc266f5c04a4a0d5122e619b09229b7c2ea2ef83f494ce1927f1a798aebe8a91bf5a12b6c0c7504e7404ebbe4f856af60b35769b0e4ef

test:
  secret_key_base: d46847b1109b6b6f6ed3d859c85ca9cfb4f263432061106af1d2b4f60cecb3a77c72370b6440dddbd8a773a3bae6ee01bf01f961dad2164a35840afdeedb032d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
